version: "3"
services:
  statservice:
    image: statservice:1.0
    ports:
      - "4003:4000"
    environment:
      PORT: 4003
      DB_HOST: postgres
      DB_PORT: 35432
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: librarydb
    volumes:
      - .:/app/
      - /app/node_modules
    command: npm run dev

    networks:
      - library-network

networks:
  library-network:
    external:
      name: postgres-network