version: "3"
services:
  postgres:
      image: postgres:latest
      ports:
        - "35432:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 123456
        POSTGRES_DB: librarydb
      volumes:
        - postgres-data:/var/lib/postgresql/data
      networks:
        - library-network

volumes:
  postgres-data:

networks:
  library-network:
    external:
      name: postgres-network