version: "3"
services:
  categoryservice:
    image: categoryservice:1.7
    ports:
      - "4002:4000"
    environment:
      - DATABASE_URL: "postgresql://postgres:123456@postgres:5432/librarydb"
    volumes:
      - .:/app/
      - /app/node_modules
    command: npm run dev

    networks:
      - library-network

networks:
  library-network:
    external:
      name: postgres-network